language: android

sudo: true

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-27
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:

  - ./gradlew testDebugUnitTest jacocoTestReport
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)